1. starting of deep_learning : 23-07-2025

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


## intro to tensors
https://docs.pytorch.org/docs/stable/tensors.html
### creating tensors


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor as a normal pt int
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim


1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors
https://docs.pytorch.org/docs/stable/generated/torch.rand.html
### what is the need to random tensors ?
Random tensors are used to **initialize model weights**, **simulate input data**, and **introduce noise or randomness** during training. They are essential for:

- **Weight Initialization** – helps break symmetry in neural networks  
- **Testing Models** – use random data before real inputs  
- **Data Augmentation** – add random noise for robustness  
- **Shuffling & Sampling** – select random batches from datasets  

**Common functions:**
- `torch.rand()` – random floats in [0, 1)  
- `torch.randn()` – random values from a normal distribution  
- `torch.randint()` – random integers in a range  

In [16]:
# Create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1348, 0.1863, 0.0131, 0.9764],
        [0.7337, 0.8484, 0.4595, 0.4065],
        [0.5887, 0.9724, 0.2828, 0.1056]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(3, 224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones


In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors like .

In [23]:
one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
#creating a random int from the range given
torch.randint(2,10, size=(1,))

tensor([3])

In [25]:
random_range = torch.arange(start=0, end=1000, step=50)
random_range

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [26]:
from re import template
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
Note: tensors datatypes is one of the 3 big errors you'll run into with Pytorch & DL
1. Tensors are not right datatypes
2. Tensors are not right shape
3. Tensors are not on the right device

In [27]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.half) # half = float16
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

## Gettig infos from tensors
1. Tensors are not right datatypes- to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors are not right shape- to get shape from a tensor, can use `tensor,shape`
3. Tensors are not on the right device- to get device from a tensor, can use `tensor.device`

In [31]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3440, 0.6010, 0.5261, 0.5532],
        [0.8866, 0.7941, 0.1196, 0.2168],
        [0.0021, 0.8198, 0.9588, 0.9961]])

In [32]:
# Find out details abt the tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3440, 0.6010, 0.5261, 0.5532],
        [0.8866, 0.7941, 0.1196, 0.2168],
        [0.0021, 0.8198, 0.9588, 0.9961]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


 ### Manipulating tensors
 it includes :
 * addition
 * subtraction
 * multiplication(element wise)
 * division
 * matrix multiplication

In [33]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor - 10

tensor([-9, -8, -7])

In [36]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor,10)

tensor([11, 12, 13])

### matrix multiplication
Two main ways of performing multiplication in neural networks and DL:
1. Element-wise multiplication
2. Matrix multiplication (dot product)
There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
 * `(3,2) @ (3,2)` won't work
 * `(3,2) @ (2,3)` will work
2. The resultiing matrix has the shape of the **outer dimensions**:
 * `(2,3) @ (3,2)` -> `(2,2)`

In [38]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")
# we can also use tensor @ tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 1.4 ms, total: 1.4 ms
Wall time: 7.99 ms


tensor(14)

In [40]:
# manual matrix multiplication
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 975 µs, sys: 0 ns, total: 975 µs
Wall time: 2.51 ms


### one of the most common erros in DL: shape errors

In [41]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a.shape, tensor_b.shape

### to fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**
  #### A **transpose** switches the axes or dimensions of a given tensor

In [43]:
tensor_b, tensor_b.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [44]:
tensor_b.T, tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
torch.mm(tensor_a, tensor_b.T) #the matrix multiplication now worked as we transposed the matrix b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [47]:
torch.mm(tensor_a, tensor_b.T).shape

torch.Size([3, 3])

### Finding the min,max,mean,sum etc (tensor aggregation)

In [60]:
#create a tensor
x = torch.arange(0,100,10)
x, x.dtype


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [57]:
#finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [55]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
#find the mean - note: the torch.mean() func requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [63]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding the positional min and max

In [64]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacing, squeezing and unsqueezing tensors
* Reshaping - reshape an input tensor to a defined tensor
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor  
* stacking- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimensions from a tensor
* unsqueeze - add a `1` dimension to the target tensor
* permute - return a view of the input with dimensions permuted (swapped) in a  certain way

In [67]:
import torch
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [72]:
# change the view
z = x.view(9,1)
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [73]:
# Changing z changes x as view of a tensor shares the same memory as the original input
z[:,0] = 5
z,x

(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [77]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked



tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [78]:
x_reshaped.shape

torch.Size([9, 1])

In [79]:
x_reshaped.squeeze().shape

torch.Size([9])

In [80]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
New shape: torch.Size([9])


In [82]:
# torch.unsqueezed() - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
#add an extra dimension with unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.]])
New shape: torch.Size([9, 1])


In [83]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [85]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## indexing (selecting data from tensors )
Indexing with pytorch is similar to indexing with numpy

In [87]:
#create tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [88]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
x[0][1]

tensor([4, 5, 6])

In [92]:
x[0][0][0]

tensor(1)

In [99]:
# you can also use ":" to select "all" of the target dimension
x[0,0,:]
x[:,:,1]

tensor([[2, 5, 8]])

## PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library
And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [101]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [102]:
array.dtype

dtype('float64')

In [103]:
tensor.dtype

torch.float64

In [106]:
torch.arange(1.0,8.0).dtype

torch.float32

In [107]:
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [113]:
a = torch.ones(7)
numpy_tensor = a.numpy()
a, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [114]:
a= a+1
a, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducebility (trying to take random out of random)
In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`
Tp reduce the randomness in nn and pytorch comes the concept of a **random seed**
Essentially what the random seed does is "flavour" the randomness


In [118]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.1882, 0.4611, 0.4152, 0.1993],
        [0.5987, 0.6865, 0.9251, 0.9654],
        [0.5126, 0.7397, 0.3393, 0.5842]])
tensor([[0.9364, 0.4155, 0.0566, 0.1739],
        [0.7020, 0.5584, 0.5150, 0.4178],
        [0.2873, 0.8282, 0.4137, 0.8858]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [120]:
# make some random but reproducible tensors using random seed
# https://en.wikipedia.org/wiki/Random_seed
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## using gpus for tensors/models


In [124]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
device
tensor= torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [126]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
