1. starting of deep_learning : 23-07-2025

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.6.0+cu124


## intro to tensors
https://docs.pytorch.org/docs/stable/tensors.html
### creating tensors


In [13]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [12]:
#get tensor as a normal pt int
scalar.item()

7

In [14]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim


1

In [17]:
vector.shape

torch.Size([2])

In [22]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [23]:
MATRIX.ndim

2

In [25]:
MATRIX[1]

tensor([ 9, 10])

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [31]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors
https://docs.pytorch.org/docs/stable/generated/torch.rand.html
### what is the need to random tensors ?
Random tensors are used to **initialize model weights**, **simulate input data**, and **introduce noise or randomness** during training. They are essential for:

- **Weight Initialization** – helps break symmetry in neural networks  
- **Testing Models** – use random data before real inputs  
- **Data Augmentation** – add random noise for robustness  
- **Shuffling & Sampling** – select random batches from datasets  

**Common functions:**
- `torch.rand()` – random floats in [0, 1)  
- `torch.randn()` – random values from a normal distribution  
- `torch.randint()` – random integers in a range  

In [35]:
# Create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8245, 0.0183, 0.4582, 0.9759],
        [0.8466, 0.2910, 0.7171, 0.4714],
        [0.9599, 0.5315, 0.3712, 0.5783]])

In [36]:
random_tensor.ndim

2

In [38]:
random_image_size_tensor = torch.rand(size=(3, 224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones


In [40]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# create a tensors of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors like .

In [54]:
one_to_ten = torch.arange(0,11)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [50]:
#creating a random int from the range given
torch.randint(2,10, size=(1,))

tensor([6])

In [56]:
random_range = torch.arange(start=0, end=1000, step=50)
random_range

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [59]:
from re import template
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes
Note: tensors datatypes is one of the 3 big errors you'll run into with Pytorch & DL
1. Tensors are not right datatypes
2. Tensors are not right shape
3. Tensors are not on the right device

In [64]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [65]:
float_32_tensor.dtype

torch.float32

In [66]:
float_16_tensor = float_32_tensor.type(torch.half) # half = float16
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [67]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])